title: Standard
icon: paragraph

status:
  draft:
    label: Entwurf
  listed:
    label: Veröffentlicht

tabs:
  content:
    label: Content
    icon: page
    columns:
      - width: 2/3
        sections:
          content:
            type: fields
            fields:
              blocks: fields/blocks
      - width: 1/3
        sections:
          files:
            headline: Alle Dateien dieser Seite
  seotab: seo
