columns:
  settingsNav:
    width: 1/1
    sections:
      nav:
        type: fields
        fields:
          navHeadline:
            label: Navigations Menüs
            type: headline
            numbered: false
          navHeader:
            width: 1/3
            type: structure
            label: Header
            fields:
              link:
                type: link
                label: Link
                required: true
                pages:
                  query: site.index.filterBy('intendedTemplate', 'in', ['default', 'home'])
                linkTypes:
                  - page
                  - url
                settings:
                  text:
                    required: true
          navFooter:
            width: 1/3
            type: structure
            label: Footer
            fields:
              link:
                type: link
                label: Link
                required: true
                pages:
                  query: site.index.filterBy('intendedTemplate', 'in', ['default', 'home'])
                linkTypes:
                  - page
                  - url
                settings:
                  text:
                    required: true
          navHambuger:
            width: 1/3
            type: structure
            label: Hamburger
            fields:
              link:
                type: link
                label: Link
                required: true
                pages:
                  query: site.index.filterBy('intendedTemplate', 'in', ['default', 'home'])
                linkTypes:
                  - page
                  - url
                settings:
                  text:
                    required: true
          line1:
            width: 1/1
            type: line
  settingsFooter:
    width: 1/1
    sections:
      footerHeadline:
        type: fields
        fields:
          footerHeadline:
            label: Footer
            type: headline
            numbered: false
      footerContent:
        type: fields
        extends: tabs/blocks
        fields:
          layout:
            label: Footer Layout

  # maintenance:
  #   type: fields
  #   fields:
  #     maintenanceHeadline:
  #       label: Wartung
  #       type: headline
  #       numbered: false
  #     maintenanceBackup:
  #       type: janitor
  #       label: Backup as .zip
  #       progress: Backing up...
  #       job: backupZip
  #     maintenanceDownload:
  #       type: janitor
  #       label: Download backup
  #       progress: Downloading...
  #       job: downloadBackup
  #     maintenanceClean:
  #       type: janitor
  #       label: Clean Content
  #       command: 'janitor:cleancontent'
  #       label: Call `Example` Command
  #     janitor_backupzip:
  #       type: janitor
  #       command: 'janitor:backupzip'
  #       cooldown: 5000
  #       label: Generate Backup ZIP
  #       icon: archive
