columns:
  settingsNav:
    width: 1/1
    sections:
      nav:
        type: fields
        fields:
          navHeadline:
            label: Navigations Menüs
            type: headline
            numbered: false
          navHeader:
            width: 1/2
            type: structure
            label: Header
            fields:
              link:
                type: link
                label: Link
                required: true
                pages:
                  query: site.index.filterBy('intendedTemplate', 'not in', ['error'])
                linkTypes:
                  - page
                  - url
                settings:
                  text:
                    required: true
          navHambuger:
            width: 1/2
            type: structure
            label: Hamburger
            fields:
              link:
                type: link
                label: Link
                required: true
                pages:
                  query: site.index.filterBy('intendedTemplate', 'not in', ['error'])
                linkTypes:
                  - page
                  - url
                settings:
                  text:
                    required: true
          line1:
            width: 1/1
            type: line
  settingsFooter:
    width: 1/1
    sections:
      footerHeadline:
        type: fields
        fields:
          footerHeadline:
            label: Footer
            type: headline
            numbered: false
      footerContent:
        type: fields
        fields:
          layoutFooter:
            label: Layout
            extends: fields/layout
            settings: tabs/config
