columns:
  settingsNav:
    width: 1/1
    sections:
      nav:
        type: fields
        fields:
          navHeadline:
            label: Navigations Menüs
            type: headline
            numbered: false
          navHeader:
            width: 1/2
            type: structure
            label: Header
            fields:
              linkObject:
                extends: fields/linkField
                fields:
                  link:
                    options:
                      - page
                      - url

          navHambuger:
            width: 1/2
            type: structure
            label: Hamburger
            fields:
              link:
                type: link
                options:
                  - page
                  - url
                  - anchor

          line1:
            width: 1/1
            type: line
  settingsFooter:
    width: 1/1
    sections:
      footerHeadline:
        type: fields
        fields:
          footerHeadline:
            label: Footer
            type: headline
            numbered: false
      footerContent:
        type: fields
        fields:
          layoutFooter:
            label: Layout
            extends: fields/layout
            settings: tabs/config
