title: Site

tabs:
  pages:
    label: Dashboard
    icon: dashboard
    columns:
      main:
        width: 1/2
        sections:
          contentMain:
            headline: Seiten / optional
            type: pages
            template:
              - default
      sidebar:
        width: 1/2
        sections:
          contentHome:
            type: pages
            label: Startseite / notwendig
            template:
              - home
              - error
            image: icon
            status: unlisted
          # sidebarDeploy:
          #   type: fields
          #   fields:
          #     deploy:
          #       type: webhook
          #       label: Deploy on Netlify
  settings:
    label: Einstellungen
    icon: settings
    extends: sections/settings
  design:
    label: Design
    icon: brush
    extends: sections/design
  seotab: seo
