title: Site

tabs:
  pages:
    label: Dashboard
    icon: dashboard
    columns:
      main:
        width: 2/3
        sections:
          contentMain:
            headline: Seiten / optional
            type: pages
            template:
              - default
      sidebar:
        width: 1/3
        sections:
          contentHome:
            type: pages
            label: Startseite / notwendig
            template:
              - home
              - error
            image: icon
            status: unlisted
          sidebarDeploy:
            type: fields
            fields:
              deploy:
                type: webhook
                label: Deploy on Netlify
  settings:
    label: Einstellungen
    icon: settings
    columns:
      settingsMenu:
        width: 1/1
        sections:
          menu:
            type: fields
            fields:
              menuHeadline:
                label: Navigations Menüs
                type: headline
                numbered: false
              menuHeader:
                width: 1/3
                label: Header
                type: pages
                query: site.index.filterBy('intendedTemplate', 'in', ['default'])
                required: false
              menuFooter:
                width: 1/3
                label: Footer
                type: pages
                query: site.index.filterBy('intendedTemplate', 'in', ['default'])
                required: false
              menuHambuger:
                width: 1/3
                label: Hamburger
                type: pages
                query: site.index.filterBy('intendedTemplate', 'in', ['default'])
                required: false
              line1:
                width: 1/1
                type: line
      settingsAddress:
        width: 2/3
        sections:
          adress:
            type: fields
            fields:
              addressHeadline:
                label: Adresse
                type: headline
                numbered: false
              addressCompany:
                label: Firma
                type: text
                width: 1/3
              addressStreet:
                label: Straße
                type: text
                width: 1/3
              addressZIP:
                label: PLZ
                type: text
                width: 1/3
              addressCity:
                label: Stadt
                type: text
                width: 1/2
              addressCountry:
                label: Land
                type: text
                width: 1/2
              addressTelephone:
                label: Telefon
                type: tel
                width: 1/2
              addressEmail:
                label: E-Mail
                type: email
                width: 1/2
              addressCompanyNumber:
                label: Firmenbuch Nummer
                type: text
                width: 1/2
              addressCourt:
                label: Zuständiges Gericht
                type: text
                width: 1/2

      settingsSocial:
        width: 1/3
        sections:
          social:
            type: fields
            fields:
              socialHeadline:
                label: Social Media
                type: headline
                numbered: false
              socialStructure:
                label: Social Media Links
                type: structure
                fields:
                  name:
                    width: 1/4
                    label: Name
                    type: text
                  url:
                    width: 2/4
                    label: URL
                    type: url
                  image:
                    width: 1/4
                    label: Bild
                    type: files
                    help: Erlaubtes Format - SVG
                    uploads:
                      template: svg
                    max: 1
                    back: white
              line2:
                type: line
          maintenance:
            type: fields
            fields:
              maintenanceHeadline:
                label: Wartung
                type: headline
                numbered: false
              maintenanceBackup:
                type: janitor
                label: Backup as .zip
                progress: Backing up...
                job: backupZip
              maintenanceDownload:
                type: janitor
                label: Download backup
                progress: Downloading...
                job: downloadBackup
  design:
    label: Design
    icon: brush
    columns:
      designHeader:
        width: 1/2
        sections:
          header:
            type: fields
            fields:
              headerHeadline:
                label: Header
                type: headline
                numbered: false
              headerLogo:
                label: Logo
                type: files
                help: Erlaubtes Format - SVG
                uploads:
                  template: svg
                multiple: false
                width: 1/2
              headerAlign:
                label: Ausrichtung
                type: select
                default: left
                options:
                  left: Links
                  center: Zentriert
                  right: Rechts
                width: 1/2

      designColors:
        width: 1/2
        sections:
          color:
            type: fields
            fields:
              colorHeadline:
                label: Farben
                type: headline
                numbered: false
              colorPrimary:
                type: colors
                label: Primäre Farbe
                default: #000000
                width: 1/3
              colorSecondary:
                type: colors
                label: Sekundäre Farbe
                width: 1/3
                default: #ffffff
              colorTertiary:
                type: colors
                label: Teritäre Farbe
                width: 1/3
                default: #aaaaaa
      designFonts:
        width: 1/1
        sections:
          font:
            type: fields
            fields:
              fontHeadline:
                label: Schriften
                type: headline
                numbered: false
              fontStructure:
                label: Schriftgrößen
                type: structure
                fields:
                  name:
                    width: 1/4
                    label: Name
                    type: text
                  fontSize:
                    width: 1/4
                    label: Schriftgröße
                    type: number
                    default: 16
                    after: px
                  fontHeight:
                    width: 1/4
                    label: Zeilenhöhe
                    type: number
                    default: 24
                    after: px
                  fontWeight:
                    width: 1/4
                    label: Schriftstärke
                    type: number
                    default: 400
                    after: px
              # fontSize-xs:
              #   label: XS-FontSize
              #   type: number
              #   default: 12
              #   after: px
              #   help: Standard 12px
              #   width: 1/6
              # fontHeight-xs:
              #   label: LineHeight-XS
              #   type: number
              #   default: 16
              #   after: px
              #   help: Standard 16px
              #   width: 1/6
              # fontSize-sm:
              #   label: SM-FontSize
              #   type: number
              #   default: 14
              #   after: px
              #   help: Standard 14px
              #   width: 1/6
              # fontHeight-sm:
              #   label: SM-LineHeight
              #   type: number
              #   default: 20
              #   after: px
              #   help: Standard 20px
              #   width: 1/6
              # fontSize-base:
              #   label: BASE-FontSize
              #   type: number
              #   default: 16
              #   after: px
              #   help: Standard 16px
              #   width: 1/6
              # fontHeight-base:
              #   label: BASE-LineHeight
              #   type: number
              #   default: 24
              #   after: px
              #   help: Standard 24px
              #   width: 1/6
              # fontSize-lg:
              #   label: LG-FontSize
              #   type: number
              #   default: 18
              #   after: px
              #   help: Standard 18px
              #   width: 1/6
              # fontHeight-lg:
              #   label: LG-LineHeight
              #   type: number
              #   default: 28
              #   after: px
              #   help: Standard 28px
              #   width: 1/6
              # fontSize-xl:
              #   label: XL-FontSize
              #   type: number
              #   default: 20
              #   after: px
              #   help: Standard 20px
              #   width: 1/6
              # fontHeight-xl:
              #   label: XL-LineHeight
              #   type: number
              #   default: 28
              #   after: px
              #   help: Standard 28px
              #   width: 1/6
              # fontSize-2xl:
              #   label: 2XL-FontSize
              #   type: number
              #   default: 24
              #   after: px
              #   help: Standard 24px
              #   width: 1/6
              # fontHeight-2xl:
              #   label: 2XL-LineHeight
              #   type: number
              #   default: 32
              #   after: px
              #   help: Standard 32px
              #   width: 1/6
              # fontSize-3xl:
              #   label: 3XL-FontSize
              #   type: number
              #   default: 30
              #   after: px
              #   help: Standard 30px
              #   width: 1/6
              # fontHeight-3xl:
              #   label: 3XL-LineHeight
              #   type: number
              #   default: 36
              #   after: px
              #   help: Standard 36px
              #   width: 1/6
              # fontSize-4xl:
              #   label: 4XL-FontSize
              #   type: number
              #   default: 36
              #   after: px
              #   help: Standard 36px
              #   width: 1/6
              # fontHeight-4xl:
              #   label: 4XL-LineHeight
              #   type: number
              #   default: 40
              #   after: px
              #   help: Standard 40px
              #   width: 1/6
              # fontSize-5xl:
              #   label: 5XL-FontSize
              #   type: number
              #   default: 48
              #   after: px
              #   help: Standard 48px
              #   width: 1/6
              # fontHeight-5xl:
              #   label: 5XL-LineHeight
              #   type: number
              #   default: 56
              #   after: px
              #   help: Standard 56px
              #   width: 1/6
              # fontSize-6xl:
              #   label: 6XL-FontSize
              #   type: number
              #   default: 64
              #   after: px
              #   help: Standard 64px
              #   width: 1/6
              # fontHeight-6xl:
              #   label: 6XL-LineHeight
              #   type: number
              #   default: 72
              #   after: px
              #   help: Standard 72px
              #   width: 1/6
              # fontSize-7xl:
              #   label: 7XL-FontSize
              #   type: number
              #   default: 72
              #   after: px
              #   help: Standard 72px
              #   width: 1/6
              # fontHeight-7xl:
              #   label: 7XL-LineHeight
              #   type: number
              #   default: 80
              #   after: px
              #   help: Standard 80px
              #   width: 1/6
              # fontSize-8xl:
              #   label: 8XL-FontSize
              #   type: number
              #   default: 96
              #   after: px
              #   help: Standard 96px
              #   width: 1/6
              # fontHeight-8xl:
              #   label: 8XL-LineHeight
              #   type: number
              #   default: 104
              #   after: px
              #   help: Standard 104px
              #   width: 1/6

  seotab: seo
